server:
  port: 8080

spring:
  main:
    lazy-initialization: true
  application:
    name: triage-copilot
  config:
    import:
      - optional:nacos:${spring.application.name}.yaml?group=${NACOS_GROUP:DEFAULT_GROUP}&refreshEnabled=true
  cloud:
    nacos:
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:nacos}
      config:
        server-addr: ${NACOS_SERVER_ADDR:nas.whpjiang.cn:8848}
        namespace: ${NACOS_NAMESPACE:}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        file-extension: yaml
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:nas.whpjiang.cn:8848}
        namespace: ${NACOS_NAMESPACE:}
        group: ${NACOS_GROUP:DEFAULT_GROUP}

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
